// Constants pour Killer Party

export const AVATARS = [
  '😎', '🥷', '🕵️', '👻', '🤡', '🎭', '🦹', '🧙',
  '🤖', '👽', '🦸', '🧛', '🧟', '🦊', '🐺', '🐯'
];

export type Language = 'fr' | 'en' | 'es' | 'de' | 'pt' | 'it' | 'zh' | 'ar';

// 🔧 FIX: Changed from array to Record so LANGUAGES[lang] works correctly
export const LANGUAGES: Record<Language, { name: string; flag: string }> = {
  fr: { name: 'Français', flag: '🇫🇷' },
  en: { name: 'English', flag: '🇬🇧' },
  es: { name: 'Español', flag: '🇪🇸' },
  de: { name: 'Deutsch', flag: '🇩🇪' },
  pt: { name: 'Português', flag: '🇵🇹' },
  it: { name: 'Italiano', flag: '🇮🇹' },
  zh: { name: '中文', flag: '🇨🇳' },
  ar: { name: 'العربية', flag: '🇸🇦' }
};

export const TRANSLATIONS: Record<Language, Record<string, string>> = {
  fr: {
    appTitle: 'Killer Party',
    createGame: '🎯 Créer une Partie',
    joinGame: '🔗 Rejoindre une Partie',
    back: '← Retour',
    codeName: 'Nom de code',
    gameCode: 'Code de la partie',
    gameMode: 'Mode de jeu',
    language: 'Langue',
    settings: 'Paramètres',
    startGame: '🚀 Lancer la Partie',
    mission: '🎯 Mission',
    feed: '📜 Feed',
    players: '👥 Joueurs',
    yourTarget: 'Ta Cible',
    killTarget: '☠️ ÉLIMINER',
    suspectHunter: '🔍 SUSPECTER QUI ME CHASSE',
    eliminate: 'Éliminer',
    scores: 'Scores',
    alive: 'En vie',
    eliminated: 'Éliminé',
    waiting: 'En attente...',
    confirmKill: "Confirmer l'élimination ?",
    cancel: 'Annuler',
    yes: 'Oui',
    no: 'Non',
    suspicionCorrect: 'Bonne suspicion !',
    suspicionIncorrect: 'Mauvaise suspicion',
    suspicions: 'Suspicions',
    eliminations: 'Éliminations',
    winner: 'Vainqueur',
    gameFinished: 'Partie Terminée',
    newGame: 'Nouvelle Partie',
    qrCodeScan: 'Scanne ce QR Code',
    shareCode: 'Partage ce code',
    useCamera: '📷 Utiliser la caméra',
    pseudo: 'Pseudo',
    resume: 'Fermer',
  },
  en: {
    appTitle: 'Killer Party',
    createGame: '🎯 Create Game',
    joinGame: '🔗 Join Game',
    back: '← Back',
    codeName: 'Code Name',
    gameCode: 'Game Code',
    gameMode: 'Game Mode',
    language: 'Language',
    settings: 'Settings',
    startGame: '🚀 Start Game',
    mission: '🎯 Mission',
    feed: '📜 Feed',
    players: '👥 Players',
    yourTarget: 'Your Target',
    killTarget: '☠️ ELIMINATE',
    suspectHunter: '🔍 SUSPECT WHO HUNTS ME',
    eliminate: 'Eliminate',
    scores: 'Scores',
    alive: 'Alive',
    eliminated: 'Eliminated',
    waiting: 'Waiting...',
    confirmKill: 'Confirm elimination?',
    cancel: 'Cancel',
    yes: 'Yes',
    no: 'No',
    suspicionCorrect: 'Correct suspicion!',
    suspicionIncorrect: 'Wrong suspicion',
    suspicions: 'Suspicions',
    eliminations: 'Eliminations',
    winner: 'Winner',
    gameFinished: 'Game Finished',
    newGame: 'New Game',
    qrCodeScan: 'Scan this QR Code',
    shareCode: 'Share this code',
    useCamera: '📷 Use camera',
    pseudo: 'Username',
    resume: 'Close',
  },
  es: {
    appTitle: 'Killer Party',
    createGame: '🎯 Crear Partida',
    joinGame: '🔗 Unirse a Partida',
    back: '← Volver',
    codeName: 'Nombre en Código',
    gameCode: 'Código de Partida',
    gameMode: 'Modo de Juego',
    language: 'Idioma',
    settings: 'Configuración',
    startGame: '🚀 Iniciar Partida',
    mission: '🎯 Misión',
    feed: '📜 Feed',
    players: '👥 Jugadores',
    yourTarget: 'Tu Objetivo',
    killTarget: '☠️ ELIMINAR',
    suspectHunter: '🔍 SOSPECHAR QUIÉN ME CAZA',
    eliminate: 'Eliminar',
    scores: 'Puntuaciones',
    alive: 'Vivo',
    eliminated: 'Eliminado',
    waiting: 'Esperando...',
    confirmKill: '¿Confirmar eliminación?',
    cancel: 'Cancelar',
    yes: 'Sí',
    no: 'No',
    suspicionCorrect: '¡Sospecha correcta!',
    suspicionIncorrect: 'Sospecha incorrecta',
    suspicions: 'Sospechas',
    eliminations: 'Eliminaciones',
    winner: 'Ganador',
    gameFinished: 'Partida Terminada',
    newGame: 'Nueva Partida',
    qrCodeScan: 'Escanea este código QR',
    shareCode: 'Comparte este código',
    useCamera: '📷 Usar cámara',
    pseudo: 'Usuario',
    resume: 'Cerrar',
  },
  de: {
    appTitle: 'Killer Party',
    createGame: '🎯 Spiel Erstellen',
    joinGame: '🔗 Spiel Beitreten',
    back: '← Zurück',
    codeName: 'Codename',
    gameCode: 'Spielcode',
    gameMode: 'Spielmodus',
    language: 'Sprache',
    settings: 'Einstellungen',
    startGame: '🚀 Spiel Starten',
    mission: '🎯 Mission',
    feed: '📜 Feed',
    players: '👥 Spieler',
    yourTarget: 'Dein Ziel',
    killTarget: '☠️ ELIMINIEREN',
    suspectHunter: '🔍 VERMUTE WER MICH JAGT',
    eliminate: 'Eliminieren',
    scores: 'Punkte',
    alive: 'Am Leben',
    eliminated: 'Eliminiert',
    waiting: 'Warten...',
    confirmKill: 'Eliminierung bestätigen?',
    cancel: 'Abbrechen',
    yes: 'Ja',
    no: 'Nein',
    suspicionCorrect: 'Richtige Vermutung!',
    suspicionIncorrect: 'Falsche Vermutung',
    suspicions: 'Vermutungen',
    eliminations: 'Eliminierungen',
    winner: 'Gewinner',
    gameFinished: 'Spiel Beendet',
    newGame: 'Neues Spiel',
    qrCodeScan: 'Scanne diesen QR-Code',
    shareCode: 'Teile diesen Code',
    useCamera: '📷 Kamera verwenden',
    pseudo: 'Benutzername',
    resume: 'Schließen',
  },
  pt: {
    appTitle: 'Killer Party',
    createGame: '🎯 Criar Partida',
    joinGame: '🔗 Entrar na Partida',
    back: '← Voltar',
    codeName: 'Nome Código',
    gameCode: 'Código da Partida',
    gameMode: 'Modo de Jogo',
    language: 'Idioma',
    settings: 'Configurações',
    startGame: '🚀 Iniciar Partida',
    mission: '🎯 Missão',
    feed: '📜 Feed',
    players: '👥 Jogadores',
    yourTarget: 'Seu Alvo',
    killTarget: '☠️ ELIMINAR',
    suspectHunter: '🔍 SUSPEITAR QUEM ME CAÇA',
    eliminate: 'Eliminar',
    scores: 'Pontuações',
    alive: 'Vivo',
    eliminated: 'Eliminado',
    waiting: 'Aguardando...',
    confirmKill: 'Confirmar eliminação?',
    cancel: 'Cancelar',
    yes: 'Sim',
    no: 'Não',
    suspicionCorrect: 'Suspeita correta!',
    suspicionIncorrect: 'Suspeita incorreta',
    suspicions: 'Suspeitas',
    eliminations: 'Eliminações',
    winner: 'Vencedor',
    gameFinished: 'Partida Terminada',
    newGame: 'Nova Partida',
    qrCodeScan: 'Escaneie este QR Code',
    shareCode: 'Compartilhe este código',
    useCamera: '📷 Usar câmera',
    pseudo: 'Nome de usuário',
    resume: 'Fechar',
  },
  it: {
    appTitle: 'Killer Party',
    createGame: '🎯 Crea Partita',
    joinGame: '🔗 Unisciti alla Partita',
    back: '← Indietro',
    codeName: 'Nome in Codice',
    gameCode: 'Codice Partita',
    gameMode: 'Modalità di Gioco',
    language: 'Lingua',
    settings: 'Impostazioni',
    startGame: '🚀 Inizia Partita',
    mission: '🎯 Missione',
    feed: '📜 Feed',
    players: '👥 Giocatori',
    yourTarget: 'Il Tuo Obiettivo',
    killTarget: '☠️ ELIMINARE',
    suspectHunter: '🔍 SOSPETTA CHI MI CACCIA',
    eliminate: 'Eliminare',
    scores: 'Punteggi',
    alive: 'Vivo',
    eliminated: 'Eliminato',
    waiting: 'In attesa...',
    confirmKill: 'Confermare eliminazione?',
    cancel: 'Annulla',
    yes: 'Sì',
    no: 'No',
    suspicionCorrect: 'Sospetto corretto!',
    suspicionIncorrect: 'Sospetto sbagliato',
    suspicions: 'Sospetti',
    eliminations: 'Eliminazioni',
    winner: 'Vincitore',
    gameFinished: 'Partita Terminata',
    newGame: 'Nuova Partita',
    qrCodeScan: 'Scansiona questo QR Code',
    shareCode: 'Condividi questo codice',
    useCamera: '📷 Usa fotocamera',
    pseudo: 'Nome utente',
    resume: 'Chiudi',
  },
  zh: {
    appTitle: 'Killer Party',
    createGame: '🎯 创建游戏',
    joinGame: '🔗 加入游戏',
    back: '← 返回',
    codeName: '代号',
    gameCode: '游戏代码',
    gameMode: '游戏模式',
    language: '语言',
    settings: '设置',
    startGame: '🚀 开始游戏',
    mission: '🎯 任务',
    feed: '📜 动态',
    players: '👥 玩家',
    yourTarget: '你的目标',
    killTarget: '☠️ 消灭',
    suspectHunter: '🔍 猜测谁在追我',
    eliminate: '消灭',
    scores: '分数',
    alive: '存活',
    eliminated: '被消灭',
    waiting: '等待中...',
    confirmKill: '确认消灭？',
    cancel: '取消',
    yes: '是',
    no: '否',
    suspicionCorrect: '猜测正确！',
    suspicionIncorrect: '猜测错误',
    suspicions: '猜测',
    eliminations: '消灭',
    winner: '获胜者',
    gameFinished: '游戏结束',
    newGame: '新游戏',
    qrCodeScan: '扫描此二维码',
    shareCode: '分享此代码',
    useCamera: '📷 使用相机',
    pseudo: '用户名',
    resume: '关闭',
  },
  ar: {
    appTitle: 'Killer Party',
    createGame: '🎯 إنشاء لعبة',
    joinGame: '🔗 الانضمام للعبة',
    back: '← رجوع',
    codeName: 'الاسم الرمزي',
    gameCode: 'كود اللعبة',
    gameMode: 'وضع اللعبة',
    language: 'اللغة',
    settings: 'الإعدادات',
    startGame: '🚀 بدء اللعبة',
    mission: '🎯 المهمة',
    feed: '📜 التغذية',
    players: '👥 اللاعبون',
    yourTarget: 'هدفك',
    killTarget: '☠️ إزالة',
    suspectHunter: '🔍 تخمين من يطاردني',
    eliminate: 'إزالة',
    scores: 'النقاط',
    alive: 'حي',
    eliminated: 'تم الإزالة',
    waiting: 'في الانتظار...',
    confirmKill: 'تأكيد الإزالة؟',
    cancel: 'إلغاء',
    yes: 'نعم',
    no: 'لا',
    suspicionCorrect: 'تخمين صحيح!',
    suspicionIncorrect: 'تخمين خاطئ',
    suspicions: 'التخمينات',
    eliminations: 'الإزالات',
    winner: 'الفائز',
    gameFinished: 'انتهت اللعبة',
    newGame: 'لعبة جديدة',
    qrCodeScan: 'امسح رمز الاستجابة السريعة',
    shareCode: 'شارك هذا الكود',
    useCamera: '📷 استخدام الكاميرا',
    pseudo: 'اسم المستخدم',
    resume: 'إغلاق',
  }
};

export const MODE_LABELS: Record<string, Record<Language, string>> = {
  FUN: {
    fr: '🎉 Fun', en: '🎉 Fun', es: '🎉 Divertido', de: '🎉 Spaß',
    pt: '🎉 Diversão', it: '🎉 Divertimento', zh: '🎉 娱乐', ar: '🎉 ممتع'
  },
  FUN_CORPORATE: {
    fr: '💼 Corporate Fun', en: '💼 Corporate Fun', es: '💼 Diversión Corporativa', de: '💼 Firmen Spaß',
    pt: '💼 Diversão Corporativa', it: '💼 Divertimento Aziendale', zh: '💼 企业娱乐', ar: '💼 متعة مؤسسية'
  },
  CHILL: {
    fr: '😌 Détente', en: '😌 Chill', es: '😌 Relajado', de: '😌 Entspannt',
    pt: '😌 Relaxado', it: '😌 Rilassato', zh: '😌 休闲', ar: '😌 استرخاء'
  }
};

export const MODE_DESCRIPTIONS: Record<string, Record<Language, string>> = {
  FUN: {
    fr: 'Missions fun et décalées', en: 'Fun and quirky missions', es: 'Misiones divertidas y originales', de: 'Lustige und verrückte Missionen',
    pt: 'Missões divertidas e originais', it: 'Missioni divertenti e originali', zh: '有趣和古怪的任务', ar: 'مهام ممتعة وغريبة'
  },
  FUN_CORPORATE: {
    fr: 'Fun mais approprié pour le travail', en: 'Fun but work-appropriate', es: 'Divertido pero apropiado para el trabajo', de: 'Spaß aber arbeitsgerecht',
    pt: 'Divertido mas apropriado para trabalho', it: 'Divertente ma appropriato per il lavoro', zh: '有趣但适合工作', ar: 'ممتع ولكن مناسب للعمل'
  },
  CHILL: {
    fr: 'Missions calmes et relaxantes', en: 'Calm and relaxing missions', es: 'Misiones tranquilas y relajantes', de: 'Ruhige und entspannende Missionen',
    pt: 'Missões calmas e relaxantes', it: 'Missioni calme e rilassanti', zh: '平静和放松的任务', ar: 'مهام هادئة ومريحة'
  }
};

// Missions par défaut
export const DEFAULT_MISSIONS: Record<string, string[]> = {
  FUN: [
    "Fais semblant de trébucher devant ta cible",
    "Propose un high-five à ta cible",
    "Chante 'Joyeux anniversaire' à ta cible",
    "Raconte une blague nulle à ta cible",
    "Imite un animal devant ta cible",
    "Fais une danse ridicule devant ta cible",
    "Demande à ta cible de te prendre en photo",
    "Propose un duel de pierre-feuille-ciseaux à ta cible",
    "Fais semblant de parler au téléphone avec quelqu'un de célèbre devant ta cible",
    "Demande à ta cible de deviner un nombre entre 1 et 10",
    "Raconte un fait inventé sur toi-même à ta cible",
    "Propose à ta cible de faire un échange de chaussures",
    "Fais semblant d'être un robot devant ta cible",
    "Demande à ta cible son avis sur une question absurde",
    "Propose un concours de regard sans cligner des yeux",
    "Fais semblant de chercher quelque chose de perdu près de ta cible",
    "Demande à ta cible de t'apprendre quelque chose",
    "Raconte l'histoire la plus courte du monde à ta cible",
    "Propose à ta cible de créer une poignée de main secrète",
    "Fais semblant d'être impressionné par quelque chose de banal devant ta cible"
  ],
  FUN_CORPORATE: [
    "Demande conseil professionnel à ta cible",
    "Propose un café à ta cible",
    "Complimente le travail de ta cible",
    "Demande l'avis de ta cible sur un projet fictif",
    "Propose une collaboration à ta cible",
    "Demande à ta cible sa routine matinale",
    "Parle de ton livre préféré avec ta cible",
    "Demande à ta cible son secret de productivité",
    "Propose une pause commune à ta cible",
    "Demande à ta cible son opinion sur un sujet d'actualité",
    "Parle de tes objectifs professionnels avec ta cible",
    "Demande à ta cible ses recommandations de lecture",
    "Propose un brainstorming sur un sujet aléatoire",
    "Demande à ta cible son meilleur conseil de carrière",
    "Parle d'un podcast intéressant avec ta cible",
    "Demande à ta cible comment elle gère son stress",
    "Propose une session de networking à ta cible",
    "Demande à ta cible son outil de travail favori",
    "Parle d'une compétence que tu veux développer",
    "Demande à ta cible ses habitudes de travail"
  ],
  CHILL: [
    "Souris à ta cible",
    "Fais un signe de la main à ta cible",
    "Dis bonjour à ta cible",
    "Demande comment va ta cible",
    "Partage une information intéressante avec ta cible",
    "Complimente quelque chose chez ta cible",
    "Demande à ta cible son humeur du jour",
    "Parle de la météo avec ta cible",
    "Demande à ta cible ce qu'elle fait ce week-end",
    "Partage ton plat préféré avec ta cible",
    "Demande à ta cible sa série préférée",
    "Parle d'un hobby avec ta cible",
    "Demande à ta cible son film préféré",
    "Partage une anecdote amusante avec ta cible",
    "Demande à ta cible sa destination de voyage de rêve",
    "Parle de musique avec ta cible",
    "Demande à ta cible son animal préféré",
    "Partage un bon souvenir avec ta cible",
    "Demande à ta cible sa saison préférée",
    "Parle d'un endroit que tu aimerais visiter"
  ]
};

export const MODE_MISSIONS = DEFAULT_MISSIONS;

export function getRandomMissions(mode: string, count: number, usedMissions: Set<string> = new Set()): string[] {
  const availableMissions = MODE_MISSIONS[mode] || MODE_MISSIONS.FUN;
  const unusedMissions = availableMissions.filter(m => !usedMissions.has(m));
  const missionPool = unusedMissions.length >= count ? unusedMissions : availableMissions;
  const shuffled = [...missionPool].sort(() => Math.random() - 0.5);
  return shuffled.slice(0, count);
}
