import React from 'react';
import { MissionCategory, Mission } from './types.ts';
import { FUN_MISSIONS, FUN_CORPORATE_MISSIONS, CHILL_MISSIONS } from './missions.ts';

export const DEFAULT_MISSIONS: Mission[] = [
  { id: '1', description: 'Faire répéter un mot complexe (ex: anticonstitutionnellement) 3 fois à votre cible.', difficulty: 2, category: MissionCategory.SOCIAL },
  { id: '2', description: 'Obtenir un selfie avec votre cible où elle sourit.', difficulty: 1, category: MissionCategory.CREATIVE },
  { id: '3', description: 'Faire chanter le refrain d\'une chanson connue à votre cible.', difficulty: 2, category: MissionCategory.PERFORMANCE },
  { id: '4', description: 'Glisser discrètement un objet dans la poche ou le sac de votre cible.', difficulty: 3, category: MissionCategory.STEALTH },
  { id: '5', description: 'Faire imiter un animal à votre cible pendant une conversation.', difficulty: 2, category: MissionCategory.HUMOR },
  { id: '6', description: 'Faire asseoir votre cible par terre sans raison apparente.', difficulty: 2, category: MissionCategory.PHYSICAL },
  { id: '7', description: 'Obtenir une poignée de main de plus de 10 secondes.', difficulty: 2, category: MissionCategory.SOCIAL },
  { id: '8', description: 'Faire dire à votre cible: "Je suis un petit poney royal".', difficulty: 3, category: MissionCategory.HUMOR },
];

export const MODE_LABELS: Record<'FUN' | 'FUN_CORPORATE' | 'CHILL', string> = {
  FUN: 'Fun',
  FUN_CORPORATE: 'Fun + Corporate',
  CHILL: 'Chill / Soft',
};

export const MODE_DESCRIPTIONS: Record<'FUN' | 'FUN_CORPORATE' | 'CHILL', string> = {
  FUN: 'Ambiance potes, délires et missions sociales.',
  FUN_CORPORATE: 'Team‑building léger, zéro gênance.',
  CHILL: 'Très doux, idéal si certains sont timides.',
};

const BASE_MISSIONS: Mission[] = [
  { id: 'b1', description: 'Faire dire à votre cible un mot en anglais au hasard.', difficulty: 1, category: MissionCategory.SOCIAL },
  { id: 'b2', description: 'Obtenir un high‑five collectif avec au moins 3 personnes.', difficulty: 1, category: MissionCategory.SOCIAL },
  { id: 'b3', description: 'Faire rire votre cible sans lui poser de question.', difficulty: 2, category: MissionCategory.HUMOR },
  { id: 'b4', description: 'Faire poser votre cible pour une photo “agent secret”.', difficulty: 1, category: MissionCategory.CREATIVE },
  { id: 'b5', description: 'Faire écrire un mot au hasard sur votre téléphone.', difficulty: 1, category: MissionCategory.LOGIC },
  { id: 'b6', description: 'Faire choisir à votre cible un objet “porte‑bonheur”.', difficulty: 1, category: MissionCategory.CREATIVE },
  { id: 'b7', description: 'Faire deviner votre pseudo à votre cible en 3 indices.', difficulty: 2, category: MissionCategory.LOGIC },
  { id: 'b8', description: 'Faire dire “mission accomplie” à votre cible.', difficulty: 1, category: MissionCategory.HUMOR },
  { id: 'b9', description: 'Faire prendre une photo de groupe avec votre cible.', difficulty: 2, category: MissionCategory.SOCIAL },
  { id: 'b10', description: 'Faire complimenter un autre joueur par votre cible.', difficulty: 2, category: MissionCategory.SOCIAL },
  { id: 'b11', description: 'Faire inventer un slogan pour la soirée.', difficulty: 2, category: MissionCategory.CREATIVE },
  { id: 'b12', description: 'Faire mimer une émotion à votre cible pendant 5 secondes.', difficulty: 2, category: MissionCategory.PERFORMANCE },
  { id: 'b13', description: 'Faire choisir un emoji qui représente la soirée.', difficulty: 1, category: MissionCategory.HUMOR },
  { id: 'b14', description: 'Faire dire à votre cible “ok chef” puis rire.', difficulty: 1, category: MissionCategory.HUMOR },
  { id: 'b15', description: 'Faire échanger un objet de poche pendant 10 secondes.', difficulty: 2, category: MissionCategory.STEALTH },
  { id: 'b16', description: 'Faire voter votre cible pour “l’accessoire le plus cool”.', difficulty: 1, category: MissionCategory.SOCIAL },
  { id: 'b17', description: 'Faire choisir un mini‑surnom à un autre joueur.', difficulty: 2, category: MissionCategory.CREATIVE },
  { id: 'b18', description: 'Faire raconter une micro‑histoire en 15 secondes.', difficulty: 2, category: MissionCategory.SOCIAL },
  { id: 'b19', description: 'Faire deviner un mot en le décrivant sans le dire.', difficulty: 2, category: MissionCategory.LOGIC },
  { id: 'b20', description: 'Faire valider un “pacte” drôle d’une phrase.', difficulty: 1, category: MissionCategory.HUMOR },
  { id: 'b21', description: 'Faire imiter un bruit discret pendant 3 secondes.', difficulty: 2, category: MissionCategory.HUMOR },
  { id: 'b22', description: 'Faire tenir un objet au‑dessus de sa tête 5 secondes.', difficulty: 1, category: MissionCategory.PHYSICAL },
  { id: 'b23', description: 'Faire dire un compliment sincère à un joueur.', difficulty: 1, category: MissionCategory.SOCIAL },
  { id: 'b24', description: 'Faire deviner un film en un mime.', difficulty: 2, category: MissionCategory.PERFORMANCE },
  { id: 'b25', description: 'Faire choisir un mot “interdit” pour 2 minutes.', difficulty: 2, category: MissionCategory.LOGIC },
  { id: 'b26', description: 'Faire dire “top secret” à voix basse.', difficulty: 1, category: MissionCategory.HUMOR },
  { id: 'b27', description: 'Faire prendre une pose “statue” pendant 5 secondes.', difficulty: 1, category: MissionCategory.PERFORMANCE },
  { id: 'b28', description: 'Faire inventer un mini‑mot de passe à 4 lettres.', difficulty: 1, category: MissionCategory.LOGIC },
  { id: 'b29', description: 'Faire échanger de place deux joueurs de la pièce.', difficulty: 2, category: MissionCategory.SOCIAL },
  { id: 'b30', description: 'Faire répondre à un “vrai ou faux” inventé.', difficulty: 1, category: MissionCategory.LOGIC },
];

const FUN_MISSIONS: Mission[] = [
  { id: 'f1', description: 'Faire chanter un mini‑refrain inventé à votre cible.', difficulty: 2, category: MissionCategory.PERFORMANCE },
  { id: 'f2', description: 'Faire prendre une pose “super‑héros” à votre cible.', difficulty: 1, category: MissionCategory.CREATIVE },
  { id: 'f3', description: 'Faire imiter un animal discret pendant 5 secondes.', difficulty: 2, category: MissionCategory.HUMOR },
  { id: 'f4', description: 'Faire raconter la pire blague possible à votre cible.', difficulty: 2, category: MissionCategory.HUMOR },
  { id: 'f5', description: 'Faire tourner sur soi‑même une fois votre cible.', difficulty: 1, category: MissionCategory.PHYSICAL },
  { id: 'f6', description: 'Faire dire “Je suis l’agent double” à votre cible.', difficulty: 1, category: MissionCategory.HUMOR },
  { id: 'f7', description: 'Faire deviner un film en un seul mot.', difficulty: 2, category: MissionCategory.LOGIC },
  { id: 'f8', description: 'Faire prendre une photo avec un objet rouge.', difficulty: 1, category: MissionCategory.CREATIVE },
  { id: 'f9', description: 'Faire inventer un nom de groupe pour vous deux.', difficulty: 2, category: MissionCategory.CREATIVE },
  { id: 'f10', description: 'Faire jouer à pierre‑feuille‑ciseaux pour un gage minuscule.', difficulty: 2, category: MissionCategory.SOCIAL },
  { id: 'f11', description: 'Faire changer de place à votre cible dans la pièce.', difficulty: 1, category: MissionCategory.SOCIAL },
  { id: 'f12', description: 'Faire dire un compliment déguisé à un autre joueur.', difficulty: 2, category: MissionCategory.SOCIAL },
  { id: 'f13', description: 'Faire choisir un thème musical pour 1 chanson.', difficulty: 1, category: MissionCategory.SOCIAL },
  { id: 'f14', description: 'Faire mimer un sport en 5 secondes.', difficulty: 2, category: MissionCategory.PERFORMANCE },
  { id: 'f15', description: 'Faire dire un mot inventé et le faire répéter.', difficulty: 2, category: MissionCategory.HUMOR },
  { id: 'f16', description: 'Faire raconter un faux “fun fact” en une phrase.', difficulty: 2, category: MissionCategory.HUMOR },
  { id: 'f17', description: 'Faire faire un mini‑toast à la soirée.', difficulty: 2, category: MissionCategory.SOCIAL },
  { id: 'f18', description: 'Faire choisir un “mot‑code” pour 10 minutes.', difficulty: 2, category: MissionCategory.LOGIC },
  { id: 'f19', description: 'Faire dessiner un smiley sur une feuille.', difficulty: 1, category: MissionCategory.CREATIVE },
  { id: 'f20', description: 'Faire deviner une chanson avec 3 mots.', difficulty: 2, category: MissionCategory.LOGIC },
  { id: 'f21', description: 'Faire faire un mini‑pas de danse (2 secondes).', difficulty: 2, category: MissionCategory.PERFORMANCE },
  { id: 'f22', description: 'Faire poser avec une grimace drôle pour une photo.', difficulty: 1, category: MissionCategory.CREATIVE },
  { id: 'f23', description: 'Faire dire “plot twist” en pleine conversation.', difficulty: 1, category: MissionCategory.HUMOR },
  { id: 'f24', description: 'Faire choisir la meilleure place de la pièce.', difficulty: 1, category: MissionCategory.SOCIAL },
  { id: 'f25', description: 'Faire décider d’un mini‑défi pour un autre joueur.', difficulty: 3, category: MissionCategory.SOCIAL },
  { id: 'f26', description: 'Faire inventer un slogan ridicule pour la soirée.', difficulty: 2, category: MissionCategory.CREATIVE },
  { id: 'f27', description: 'Faire deviner une célébrité en 2 indices.', difficulty: 2, category: MissionCategory.LOGIC },
  { id: 'f28', description: 'Faire choisir un emoji interdit pendant 5 minutes.', difficulty: 2, category: MissionCategory.LOGIC },
  { id: 'f29', description: 'Faire crier “victoire” très doucement.', difficulty: 1, category: MissionCategory.HUMOR },
  { id: 'f30', description: 'Faire raconter une anecdote “embarrassante” soft.', difficulty: 2, category: MissionCategory.SOCIAL },
];

const FUN_CORPORATE_MISSIONS: Mission[] = [
  { id: 'c1', description: 'Faire proposer un “titre de poste” amusant à votre cible.', difficulty: 1, category: MissionCategory.CREATIVE },
  { id: 'c2', description: 'Faire donner un feedback positif à un joueur.', difficulty: 1, category: MissionCategory.SOCIAL },
  { id: 'c3', description: 'Faire décrire sa “valeur” en un mot.', difficulty: 1, category: MissionCategory.LOGIC },
  { id: 'c4', description: 'Faire inventer un slogan d’équipe en 5 mots.', difficulty: 2, category: MissionCategory.CREATIVE },
  { id: 'c5', description: 'Faire mimer une réunion sans paroles pendant 5 secondes.', difficulty: 2, category: MissionCategory.HUMOR },
  { id: 'c6', description: 'Faire définir un “objectif de soirée” en une phrase.', difficulty: 1, category: MissionCategory.SOCIAL },
  { id: 'c7', description: 'Faire voter votre cible pour un “agent du mois”.', difficulty: 2, category: MissionCategory.SOCIAL },
  { id: 'c8', description: 'Faire donner un conseil de productivité absurde.', difficulty: 2, category: MissionCategory.HUMOR },
  { id: 'c9', description: 'Faire créer un nom de projet pour la soirée.', difficulty: 2, category: MissionCategory.CREATIVE },
  { id: 'c10', description: 'Faire dire “aligné et impactant” à votre cible.', difficulty: 1, category: MissionCategory.HUMOR },
  { id: 'c11', description: 'Faire inventer un KPI drôle pour la soirée.', difficulty: 2, category: MissionCategory.LOGIC },
  { id: 'c12', description: 'Faire demander à un joueur “tu peux te sync ?”.', difficulty: 2, category: MissionCategory.HUMOR },
  { id: 'c13', description: 'Faire choisir un “mot‑buzz” pour 5 minutes.', difficulty: 2, category: MissionCategory.SOCIAL },
  { id: 'c14', description: 'Faire définir la soirée en 3 adjectifs.', difficulty: 1, category: MissionCategory.LOGIC },
  { id: 'c15', description: 'Faire inventer un nom de squad pour le groupe.', difficulty: 2, category: MissionCategory.CREATIVE },
  { id: 'c16', description: 'Faire attribuer un “prix” drôle à quelqu’un.', difficulty: 2, category: MissionCategory.SOCIAL },
  { id: 'c17', description: 'Faire proposer un plan en 3 étapes pour “réussir la soirée”.', difficulty: 2, category: MissionCategory.LOGIC },
  { id: 'c18', description: 'Faire donner une “leçon apprise” en une phrase.', difficulty: 1, category: MissionCategory.SOCIAL },
  { id: 'c19', description: 'Faire inventer un logo imaginaire pour la soirée.', difficulty: 2, category: MissionCategory.CREATIVE },
  { id: 'c20', description: 'Faire mimer un call en visio pendant 5 secondes.', difficulty: 2, category: MissionCategory.HUMOR },
  { id: 'c21', description: 'Faire choisir un “sprint” de 2 minutes de silence.', difficulty: 2, category: MissionCategory.LOGIC },
  { id: 'c22', description: 'Faire décider d’une “mission collective” douce.', difficulty: 2, category: MissionCategory.SOCIAL },
  { id: 'c23', description: 'Faire résumer la soirée en un “slide title”.', difficulty: 2, category: MissionCategory.CREATIVE },
  { id: 'c24', description: 'Faire dire “on est alignés” avec un clin d’œil.', difficulty: 1, category: MissionCategory.HUMOR },
  { id: 'c25', description: 'Faire choisir un “chef de projet” imaginaire.', difficulty: 1, category: MissionCategory.SOCIAL },
  { id: 'c26', description: 'Faire inventer un motto de 4 mots.', difficulty: 2, category: MissionCategory.CREATIVE },
  { id: 'c27', description: 'Faire proposer une règle fun pour 10 minutes.', difficulty: 2, category: MissionCategory.SOCIAL },
  { id: 'c28', description: 'Faire donner un “status update” en 10 secondes.', difficulty: 2, category: MissionCategory.HUMOR },
  { id: 'c29', description: 'Faire choisir un “OKR” absurdement simple.', difficulty: 2, category: MissionCategory.LOGIC },
  { id: 'c30', description: 'Faire dire “let’s circle back” en pleine phrase.', difficulty: 1, category: MissionCategory.HUMOR },
];

const CHILL_MISSIONS: Mission[] = [
  { id: 's1', description: 'Faire choisir une chanson “ambiance chill”.', difficulty: 1, category: MissionCategory.SOCIAL },
  { id: 's2', description: 'Faire décrire un souvenir sympa en une phrase.', difficulty: 1, category: MissionCategory.SOCIAL },
  { id: 's3', description: 'Faire proposer un snack idéal pour la soirée.', difficulty: 1, category: MissionCategory.CREATIVE },
  { id: 's4', description: 'Faire répondre à un mini‑quiz: “thé ou café ?”.', difficulty: 1, category: MissionCategory.LOGIC },
  { id: 's5', description: 'Faire écrire un emoji qui décrit son humeur.', difficulty: 1, category: MissionCategory.HUMOR },
  { id: 's6', description: 'Faire choisir une couleur qui représente la soirée.', difficulty: 1, category: MissionCategory.CREATIVE },
  { id: 's7', description: 'Faire raconter une anecdote en 10 secondes.', difficulty: 2, category: MissionCategory.SOCIAL },
  { id: 's8', description: 'Faire proposer une activité “tranquille” à faire.', difficulty: 1, category: MissionCategory.SOCIAL },
  { id: 's9', description: 'Faire deviner un mot avec un seul geste.', difficulty: 2, category: MissionCategory.PERFORMANCE },
  { id: 's10', description: 'Faire envoyer un “merci” à un autre joueur.', difficulty: 1, category: MissionCategory.SOCIAL },
  { id: 's11', description: 'Faire dire “on garde le flow”.', difficulty: 1, category: MissionCategory.HUMOR },
  { id: 's12', description: 'Faire choisir un coin “calme” dans la maison.', difficulty: 1, category: MissionCategory.SOCIAL },
  { id: 's13', description: 'Faire choisir un “moment chill” de la soirée.', difficulty: 1, category: MissionCategory.SOCIAL },
  { id: 's14', description: 'Faire proposer un jeu soft en une phrase.', difficulty: 1, category: MissionCategory.SOCIAL },
  { id: 's15', description: 'Faire dire un mot positif sur quelqu’un.', difficulty: 1, category: MissionCategory.SOCIAL },
  { id: 's16', description: 'Faire choisir une boisson sans alcool préférée.', difficulty: 1, category: MissionCategory.SOCIAL },
  { id: 's17', description: 'Faire raconter un souvenir drôle mais doux.', difficulty: 2, category: MissionCategory.SOCIAL },
  { id: 's18', description: 'Faire proposer un “bon plan” pour se détendre.', difficulty: 1, category: MissionCategory.SOCIAL },
  { id: 's19', description: 'Faire choisir un mot “cool” à dire ce soir.', difficulty: 1, category: MissionCategory.HUMOR },
  { id: 's20', description: 'Faire choisir une couleur pour l’ambiance.', difficulty: 1, category: MissionCategory.CREATIVE },
  { id: 's21', description: 'Faire poser une question “préférerais‑tu” soft.', difficulty: 2, category: MissionCategory.LOGIC },
  { id: 's22', description: 'Faire proposer un coin photo pour la soirée.', difficulty: 1, category: MissionCategory.CREATIVE },
  { id: 's23', description: 'Faire choisir un “rituel” léger (ex: toast).', difficulty: 1, category: MissionCategory.SOCIAL },
  { id: 's24', description: 'Faire dire un mot de bienvenue à quelqu’un.', difficulty: 1, category: MissionCategory.SOCIAL },
  { id: 's25', description: 'Faire choisir un son qui représente la soirée.', difficulty: 1, category: MissionCategory.HUMOR },
  { id: 's26', description: 'Faire proposer un mini‑défi ultra simple.', difficulty: 2, category: MissionCategory.SOCIAL },
  { id: 's27', description: 'Faire deviner un objet présent dans la pièce.', difficulty: 2, category: MissionCategory.LOGIC },
  { id: 's28', description: 'Faire dire “pause” et sourire.', difficulty: 1, category: MissionCategory.HUMOR },
  { id: 's29', description: 'Faire choisir un mot “secret” pour 2 minutes.', difficulty: 2, category: MissionCategory.LOGIC },
  { id: 's30', description: 'Faire proposer une règle “respect” rigolote.', difficulty: 1, category: MissionCategory.SOCIAL },
];

export const MODE_MISSIONS: Record<'FUN' | 'FUN_CORPORATE' | 'CHILL', Mission[]> = {
  FUN: FUN_MISSIONS,
  FUN_CORPORATE: FUN_CORPORATE_MISSIONS,
  CHILL: CHILL_MISSIONS,
};

export const AVATARS = [
  'https://api.dicebear.com/8.x/identicon/svg?seed=shadow',
  'https://api.dicebear.com/8.x/identicon/svg?seed=night',
  'https://api.dicebear.com/8.x/identicon/svg?seed=phantom',
  'https://api.dicebear.com/8.x/identicon/svg?seed=omega',
  'https://api.dicebear.com/8.x/identicon/svg?seed=apollo',
  'https://api.dicebear.com/8.x/identicon/svg?seed=echo',
];
