import { Mission, MissionCategory } from './types.ts';

export const FUN_MISSIONS: Mission[] = [
  { id: 'f001', description: 'Faire dire “on est chauds” puis sourire.', difficulty: 1, category: MissionCategory.HUMOR },
  { id: 'f002', description: 'Faire choisir une chanson pour la prochaine minute.', difficulty: 1, category: MissionCategory.SOCIAL },
  { id: 'f003', description: 'Faire mimer un animal pendant 3 secondes.', difficulty: 2, category: MissionCategory.PERFORMANCE },
  { id: 'f004', description: 'Faire inventer un slogan pour la soirée.', difficulty: 2, category: MissionCategory.CREATIVE },
  { id: 'f005', description: 'Faire poser pour une photo “dramatic light”.', difficulty: 1, category: MissionCategory.CREATIVE },
  { id: 'f006', description: 'Faire deviner un film en un mot.', difficulty: 2, category: MissionCategory.LOGIC },
  { id: 'f007', description: 'Faire dire un mot inventé et le faire répéter.', difficulty: 2, category: MissionCategory.HUMOR },
  { id: 'f008', description: 'Faire réaliser un mini toast à la soirée.', difficulty: 2, category: MissionCategory.SOCIAL },
  { id: 'f009', description: 'Faire choisir un mot interdit pendant 2 minutes.', difficulty: 2, category: MissionCategory.LOGIC },
  { id: 'f010', description: 'Faire inventer un nom de duo pour vous deux.', difficulty: 2, category: MissionCategory.CREATIVE },
  { id: 'f011', description: 'Faire chanter un micro‑refrain de 3 mots.', difficulty: 2, category: MissionCategory.PERFORMANCE },
  { id: 'f012', description: 'Faire dire “plot twist” en pleine phrase.', difficulty: 1, category: MissionCategory.HUMOR },
  { id: 'f013', description: 'Faire deviner une célébrité en 2 indices.', difficulty: 2, category: MissionCategory.LOGIC },
  { id: 'f014', description: 'Faire faire un mini pas de danse (2 secondes).', difficulty: 2, category: MissionCategory.PERFORMANCE },
  { id: 'f015', description: 'Faire poser avec une grimace drôle pour une photo.', difficulty: 1, category: MissionCategory.CREATIVE },
  { id: 'f016', description: 'Faire dire “mission accomplie” en chuchotant.', difficulty: 1, category: MissionCategory.HUMOR },
  { id: 'f017', description: 'Faire choisir l’accessoire le plus stylé de la pièce.', difficulty: 1, category: MissionCategory.SOCIAL },
  { id: 'f018', description: 'Faire raconter une blague très courte.', difficulty: 2, category: MissionCategory.HUMOR },
  { id: 'f019', description: 'Faire faire un high‑five à 3 personnes.', difficulty: 1, category: MissionCategory.SOCIAL },
  { id: 'f020', description: 'Faire mimer un sport en 5 secondes.', difficulty: 2, category: MissionCategory.PERFORMANCE },
  { id: 'f021', description: 'Faire choisir un emoji qui décrit la soirée.', difficulty: 1, category: MissionCategory.HUMOR },
  { id: 'f022', description: 'Faire inventer un mot de passe de 4 lettres.', difficulty: 1, category: MissionCategory.LOGIC },
  { id: 'f023', description: 'Faire proposer une règle fun pour 5 minutes.', difficulty: 2, category: MissionCategory.SOCIAL },
  { id: 'f024', description: 'Faire dire un compliment déguisé à quelqu’un.', difficulty: 2, category: MissionCategory.SOCIAL },
  { id: 'f025', description: 'Faire prendre une photo avec un objet rouge.', difficulty: 1, category: MissionCategory.CREATIVE },
  { id: 'f026', description: 'Faire deviner une chanson en 3 mots.', difficulty: 2, category: MissionCategory.LOGIC },
  { id: 'f027', description: 'Faire choisir la meilleure place de la pièce.', difficulty: 1, category: MissionCategory.SOCIAL },
  { id: 'f028', description: 'Faire dire “c’est validé” très sérieusement.', difficulty: 1, category: MissionCategory.HUMOR },
  { id: 'f029', description: 'Faire inventer une poignée de main spéciale.', difficulty: 3, category: MissionCategory.CREATIVE },
  { id: 'f030', description: 'Faire poser en “statue” pendant 5 secondes.', difficulty: 1, category: MissionCategory.PERFORMANCE },
  { id: 'f031', description: 'Faire citer un film culte sans le nommer.', difficulty: 2, category: MissionCategory.LOGIC },
  { id: 'f032', description: 'Faire dire “ok chef” puis rire.', difficulty: 1, category: MissionCategory.HUMOR },
  { id: 'f033', description: 'Faire proposer un défi ultra simple à quelqu’un.', difficulty: 2, category: MissionCategory.SOCIAL },
  { id: 'f034', description: 'Faire inventer un slogan ridicule en 5 mots.', difficulty: 2, category: MissionCategory.CREATIVE },
  { id: 'f035', description: 'Faire dire un mot en anglais au hasard.', difficulty: 1, category: MissionCategory.SOCIAL },
  { id: 'f036', description: 'Faire deviner un objet présent dans la pièce.', difficulty: 2, category: MissionCategory.LOGIC },
  { id: 'f037', description: 'Faire mimer une émotion pendant 5 secondes.', difficulty: 2, category: MissionCategory.PERFORMANCE },
  { id: 'f038', description: 'Faire dire “top secret” à voix basse.', difficulty: 1, category: MissionCategory.HUMOR },
  { id: 'f039', description: 'Faire inventer un pseudo pour un autre joueur.', difficulty: 2, category: MissionCategory.CREATIVE },
  { id: 'f040', description: 'Faire dessiner un smiley sur une feuille.', difficulty: 1, category: MissionCategory.CREATIVE },
  { id: 'f041', description: 'Faire raconter un faux “fun fact”.', difficulty: 2, category: MissionCategory.HUMOR },
  { id: 'f042', description: 'Faire choisir un mini mot‑code pour 5 minutes.', difficulty: 2, category: MissionCategory.LOGIC },
  { id: 'f043', description: 'Faire dire “on se comprend” en clin d’œil.', difficulty: 1, category: MissionCategory.HUMOR },
  { id: 'f044', description: 'Faire deviner une couleur en la décrivant.', difficulty: 1, category: MissionCategory.LOGIC },
  { id: 'f045', description: 'Faire proposer un thème musical pour 1 chanson.', difficulty: 1, category: MissionCategory.SOCIAL },
  { id: 'f046', description: 'Faire faire une mini danse de 3 secondes.', difficulty: 2, category: MissionCategory.PERFORMANCE },
  { id: 'f047', description: 'Faire poser pour une photo “sérieux”.', difficulty: 1, category: MissionCategory.CREATIVE },
  { id: 'f048', description: 'Faire dire “c’est carré” à quelqu’un.', difficulty: 1, category: MissionCategory.HUMOR },
  { id: 'f049', description: 'Faire inventer un nom d’équipe pour la soirée.', difficulty: 2, category: MissionCategory.CREATIVE },
  { id: 'f050', description: 'Faire choisir un emoji interdit pendant 5 minutes.', difficulty: 2, category: MissionCategory.LOGIC },
  { id: 'f051', description: 'Faire raconter une anecdote en 15 secondes.', difficulty: 2, category: MissionCategory.SOCIAL },
  { id: 'f052', description: 'Faire dire “plot twist” à quelqu’un d’autre.', difficulty: 1, category: MissionCategory.HUMOR },
  { id: 'f053', description: 'Faire choisir un coin photo pour la soirée.', difficulty: 1, category: MissionCategory.CREATIVE },
  { id: 'f054', description: 'Faire deviner un animal par un geste.', difficulty: 2, category: MissionCategory.PERFORMANCE },
  { id: 'f055', description: 'Faire dire “validé” en duo avec toi.', difficulty: 1, category: MissionCategory.SOCIAL },
  { id: 'f056', description: 'Faire inventer une mini règle drôle.', difficulty: 2, category: MissionCategory.SOCIAL },
  { id: 'f057', description: 'Faire choisir un objet porte‑bonheur.', difficulty: 1, category: MissionCategory.CREATIVE },
  { id: 'f058', description: 'Faire dire un mot qui rime avec “soirée”.', difficulty: 1, category: MissionCategory.LOGIC },
  { id: 'f059', description: 'Faire choisir une couleur “officielle” du groupe.', difficulty: 1, category: MissionCategory.SOCIAL },
  { id: 'f060', description: 'Faire inventer un jingle de 3 secondes.', difficulty: 3, category: MissionCategory.PERFORMANCE },
  { id: 'f061', description: 'Faire proposer une mini mission pour quelqu’un.', difficulty: 2, category: MissionCategory.SOCIAL },
  { id: 'f062', description: 'Faire raconter une histoire en 10 mots.', difficulty: 2, category: MissionCategory.CREATIVE },
  { id: 'f063', description: 'Faire dire “on est ensemble”.', difficulty: 1, category: MissionCategory.SOCIAL },
  { id: 'f064', description: 'Faire imiter un rire célèbre pendant 2 secondes.', difficulty: 2, category: MissionCategory.HUMOR },
  { id: 'f065', description: 'Faire proposer un toast sans boisson.', difficulty: 2, category: MissionCategory.HUMOR },
  { id: 'f066', description: 'Faire deviner un métier en 2 indices.', difficulty: 2, category: MissionCategory.LOGIC },
  { id: 'f067', description: 'Faire dire “je confirme” d’un ton sérieux.', difficulty: 1, category: MissionCategory.HUMOR },
  { id: 'f068', description: 'Faire choisir un mot “secret” pour 3 minutes.', difficulty: 2, category: MissionCategory.LOGIC },
  { id: 'f069', description: 'Faire prendre une photo de groupe rapide.', difficulty: 2, category: MissionCategory.SOCIAL },
  { id: 'f070', description: 'Faire poser en “super‑héros” avec toi.', difficulty: 1, category: MissionCategory.CREATIVE },
  { id: 'f071', description: 'Faire dire “tout est sous contrôle”.', difficulty: 1, category: MissionCategory.HUMOR },
  { id: 'f072', description: 'Faire deviner un fruit en 3 mots.', difficulty: 1, category: MissionCategory.LOGIC },
  { id: 'f073', description: 'Faire proposer un mini jeu de 30 secondes.', difficulty: 2, category: MissionCategory.SOCIAL },
  { id: 'f074', description: 'Faire raconter un souvenir drôle mais soft.', difficulty: 2, category: MissionCategory.SOCIAL },
  { id: 'f075', description: 'Faire dire “c’est la vibe”.', difficulty: 1, category: MissionCategory.HUMOR },
  { id: 'f076', description: 'Faire inventer un clap de fin.', difficulty: 2, category: MissionCategory.CREATIVE },
  { id: 'f077', description: 'Faire mimer un objet en 5 secondes.', difficulty: 2, category: MissionCategory.PERFORMANCE },
  { id: 'f078', description: 'Faire choisir un surnom pour un duo.', difficulty: 2, category: MissionCategory.CREATIVE },
  { id: 'f079', description: 'Faire dire “j’ai capté”.', difficulty: 1, category: MissionCategory.HUMOR },
  { id: 'f080', description: 'Faire deviner un animal en un seul geste.', difficulty: 2, category: MissionCategory.PERFORMANCE },
  { id: 'f081', description: 'Faire inventer une règle “silence 10 secondes”.', difficulty: 2, category: MissionCategory.SOCIAL },
  { id: 'f082', description: 'Faire dire “let’s go” discrètement.', difficulty: 1, category: MissionCategory.HUMOR },
  { id: 'f083', description: 'Faire choisir un objet “totem”.', difficulty: 1, category: MissionCategory.CREATIVE },
  { id: 'f084', description: 'Faire dire une phrase en rime.', difficulty: 2, category: MissionCategory.LOGIC },
  { id: 'f085', description: 'Faire proposer une mini pause photo.', difficulty: 1, category: MissionCategory.SOCIAL },
  { id: 'f086', description: 'Faire deviner un pays en 2 indices.', difficulty: 2, category: MissionCategory.LOGIC },
  { id: 'f087', description: 'Faire mimer un personnage connu.', difficulty: 2, category: MissionCategory.PERFORMANCE },
  { id: 'f088', description: 'Faire dire “validé par le jury”.', difficulty: 1, category: MissionCategory.HUMOR },
  { id: 'f089', description: 'Faire inventer un nom de soirée.', difficulty: 2, category: MissionCategory.CREATIVE },
  { id: 'f090', description: 'Faire choisir une règle fun pour 3 minutes.', difficulty: 2, category: MissionCategory.SOCIAL },
  { id: 'f091', description: 'Faire dire “ok on bouge”.', difficulty: 1, category: MissionCategory.HUMOR },
  { id: 'f092', description: 'Faire deviner un animal avec un son.', difficulty: 2, category: MissionCategory.PERFORMANCE },
  { id: 'f093', description: 'Faire raconter un rêve étrange en 10 secondes.', difficulty: 2, category: MissionCategory.SOCIAL },
  { id: 'f094', description: 'Faire dire “ça passe crème”.', difficulty: 1, category: MissionCategory.HUMOR },
  { id: 'f095', description: 'Faire inventer un mot‑code en 4 lettres.', difficulty: 1, category: MissionCategory.LOGIC },
  { id: 'f096', description: 'Faire choisir un mot “sacré” pour 2 minutes.', difficulty: 2, category: MissionCategory.LOGIC },
  { id: 'f097', description: 'Faire proposer un plan fun pour plus tard.', difficulty: 1, category: MissionCategory.SOCIAL },
  { id: 'f098', description: 'Faire mimer un objet de la cuisine.', difficulty: 2, category: MissionCategory.PERFORMANCE },
  { id: 'f099', description: 'Faire dire “c’est notre secret”.', difficulty: 1, category: MissionCategory.HUMOR },
  { id: 'f100', description: 'Faire inventer un cri de ralliement discret.', difficulty: 2, category: MissionCategory.CREATIVE },
];

export const FUN_CORPORATE_MISSIONS: Mission[] = [
  { id: 'c001', description: 'Faire proposer un “titre de poste” fun.', difficulty: 1, category: MissionCategory.CREATIVE },
  { id: 'c002', description: 'Faire donner un feedback positif à quelqu’un.', difficulty: 1, category: MissionCategory.SOCIAL },
  { id: 'c003', description: 'Faire décrire sa “valeur” en un mot.', difficulty: 1, category: MissionCategory.LOGIC },
  { id: 'c004', description: 'Faire inventer un slogan d’équipe en 5 mots.', difficulty: 2, category: MissionCategory.CREATIVE },
  { id: 'c005', description: 'Faire mimer une réunion sans paroles (5 s).', difficulty: 2, category: MissionCategory.HUMOR },
  { id: 'c006', description: 'Faire définir un “objectif de soirée”.', difficulty: 1, category: MissionCategory.SOCIAL },
  { id: 'c007', description: 'Faire voter pour un “joueur du mois”.', difficulty: 2, category: MissionCategory.SOCIAL },
  { id: 'c008', description: 'Faire donner un conseil productivité absurde.', difficulty: 2, category: MissionCategory.HUMOR },
  { id: 'c009', description: 'Faire créer un nom de projet pour la soirée.', difficulty: 2, category: MissionCategory.CREATIVE },
  { id: 'c010', description: 'Faire dire “aligné et impactant”.', difficulty: 1, category: MissionCategory.HUMOR },
  { id: 'c011', description: 'Faire inventer un KPI drôle.', difficulty: 2, category: MissionCategory.LOGIC },
  { id: 'c012', description: 'Faire demander “tu peux te sync ?”.', difficulty: 2, category: MissionCategory.HUMOR },
  { id: 'c013', description: 'Faire choisir un “mot‑buzz” pour 5 minutes.', difficulty: 2, category: MissionCategory.SOCIAL },
  { id: 'c014', description: 'Faire définir la soirée en 3 adjectifs.', difficulty: 1, category: MissionCategory.LOGIC },
  { id: 'c015', description: 'Faire inventer un nom de squad pour le groupe.', difficulty: 2, category: MissionCategory.CREATIVE },
  { id: 'c016', description: 'Faire attribuer un “prix” drôle à quelqu’un.', difficulty: 2, category: MissionCategory.SOCIAL },
  { id: 'c017', description: 'Faire proposer un plan en 3 étapes.', difficulty: 2, category: MissionCategory.LOGIC },
  { id: 'c018', description: 'Faire donner une “leçon apprise”.', difficulty: 1, category: MissionCategory.SOCIAL },
  { id: 'c019', description: 'Faire inventer un logo imaginaire.', difficulty: 2, category: MissionCategory.CREATIVE },
  { id: 'c020', description: 'Faire mimer un call visio (5 s).', difficulty: 2, category: MissionCategory.HUMOR },
  { id: 'c021', description: 'Faire choisir un “sprint” de 2 minutes.', difficulty: 2, category: MissionCategory.LOGIC },
  { id: 'c022', description: 'Faire décider d’une mission collective douce.', difficulty: 2, category: MissionCategory.SOCIAL },
  { id: 'c023', description: 'Faire résumer la soirée en un slide title.', difficulty: 2, category: MissionCategory.CREATIVE },
  { id: 'c024', description: 'Faire dire “on est alignés” avec un clin d’œil.', difficulty: 1, category: MissionCategory.HUMOR },
  { id: 'c025', description: 'Faire choisir un “chef de projet” imaginaire.', difficulty: 1, category: MissionCategory.SOCIAL },
  { id: 'c026', description: 'Faire inventer un motto de 4 mots.', difficulty: 2, category: MissionCategory.CREATIVE },
  { id: 'c027', description: 'Faire proposer une règle fun pour 10 minutes.', difficulty: 2, category: MissionCategory.SOCIAL },
  { id: 'c028', description: 'Faire donner un status update en 10 secondes.', difficulty: 2, category: MissionCategory.HUMOR },
  { id: 'c029', description: 'Faire choisir un OKR absurde.', difficulty: 2, category: MissionCategory.LOGIC },
  { id: 'c030', description: 'Faire dire “let’s circle back”.', difficulty: 1, category: MissionCategory.HUMOR },
  { id: 'c031', description: 'Faire inventer un mini organigramme.', difficulty: 2, category: MissionCategory.CREATIVE },
  { id: 'c032', description: 'Faire définir un risque en une phrase.', difficulty: 2, category: MissionCategory.LOGIC },
  { id: 'c033', description: 'Faire proposer un “quick win”.', difficulty: 1, category: MissionCategory.SOCIAL },
  { id: 'c034', description: 'Faire dire “on escalade ?”.', difficulty: 1, category: MissionCategory.HUMOR },
  { id: 'c035', description: 'Faire inventer un nom de réunion.', difficulty: 2, category: MissionCategory.CREATIVE },
  { id: 'c036', description: 'Faire donner une mission “post‑it”.', difficulty: 2, category: MissionCategory.SOCIAL },
  { id: 'c037', description: 'Faire proposer un plan de 3 mots.', difficulty: 1, category: MissionCategory.LOGIC },
  { id: 'c038', description: 'Faire dire “roadmap validée”.', difficulty: 1, category: MissionCategory.HUMOR },
  { id: 'c039', description: 'Faire inventer un slogan motivant.', difficulty: 2, category: MissionCategory.CREATIVE },
  { id: 'c040', description: 'Faire nommer un “owner” de la soirée.', difficulty: 1, category: MissionCategory.SOCIAL },
  { id: 'c041', description: 'Faire proposer une action “next step”.', difficulty: 2, category: MissionCategory.LOGIC },
  { id: 'c042', description: 'Faire dire “priorité numéro 1”.', difficulty: 1, category: MissionCategory.HUMOR },
  { id: 'c043', description: 'Faire inventer une mini charte de la soirée.', difficulty: 2, category: MissionCategory.CREATIVE },
  { id: 'c044', description: 'Faire donner un feedback “sandwich”.', difficulty: 2, category: MissionCategory.SOCIAL },
  { id: 'c045', description: 'Faire proposer un score de satisfaction.', difficulty: 2, category: MissionCategory.LOGIC },
  { id: 'c046', description: 'Faire dire “on est sur la même page”.', difficulty: 1, category: MissionCategory.HUMOR },
  { id: 'c047', description: 'Faire inventer un mini rituel d’équipe.', difficulty: 2, category: MissionCategory.CREATIVE },
  { id: 'c048', description: 'Faire choisir un “risk owner”.', difficulty: 1, category: MissionCategory.SOCIAL },
  { id: 'c049', description: 'Faire proposer un plan d’action en 2 mots.', difficulty: 1, category: MissionCategory.LOGIC },
  { id: 'c050', description: 'Faire dire “on aligne les planètes”.', difficulty: 1, category: MissionCategory.HUMOR },
  { id: 'c051', description: 'Faire inventer un nom de feature.', difficulty: 2, category: MissionCategory.CREATIVE },
  { id: 'c052', description: 'Faire choisir un indicateur “plaisir”.', difficulty: 2, category: MissionCategory.LOGIC },
  { id: 'c053', description: 'Faire proposer une mini démo de 10 s.', difficulty: 2, category: MissionCategory.SOCIAL },
  { id: 'c054', description: 'Faire dire “on se sync” en duo.', difficulty: 1, category: MissionCategory.HUMOR },
  { id: 'c055', description: 'Faire inventer un mini pitch de 1 phrase.', difficulty: 2, category: MissionCategory.CREATIVE },
  { id: 'c056', description: 'Faire choisir un nom pour une équipe.', difficulty: 2, category: MissionCategory.SOCIAL },
  { id: 'c057', description: 'Faire dire “merci pour le check‑in”.', difficulty: 1, category: MissionCategory.HUMOR },
  { id: 'c058', description: 'Faire proposer un plan “B” en 1 mot.', difficulty: 1, category: MissionCategory.LOGIC },
  { id: 'c059', description: 'Faire inventer un badge imaginaire.', difficulty: 2, category: MissionCategory.CREATIVE },
  { id: 'c060', description: 'Faire choisir un “owner du fun”.', difficulty: 1, category: MissionCategory.SOCIAL },
  { id: 'c061', description: 'Faire dire “on est alignés” en chuchotant.', difficulty: 1, category: MissionCategory.HUMOR },
  { id: 'c062', description: 'Faire proposer un “quick retro” de 5 mots.', difficulty: 2, category: MissionCategory.LOGIC },
  { id: 'c063', description: 'Faire inventer un mini KPI “énergie”.', difficulty: 2, category: MissionCategory.LOGIC },
  { id: 'c064', description: 'Faire choisir un nom de réunion fun.', difficulty: 2, category: MissionCategory.CREATIVE },
  { id: 'c065', description: 'Faire dire “on fait un point”.', difficulty: 1, category: MissionCategory.HUMOR },
  { id: 'c066', description: 'Faire proposer un slogan en 3 mots.', difficulty: 1, category: MissionCategory.CREATIVE },
  { id: 'c067', description: 'Faire choisir un “owner du snack”.', difficulty: 1, category: MissionCategory.SOCIAL },
  { id: 'c068', description: 'Faire dire “aligned”.', difficulty: 1, category: MissionCategory.HUMOR },
  { id: 'c069', description: 'Faire inventer un mini deck de 3 titres.', difficulty: 2, category: MissionCategory.CREATIVE },
  { id: 'c070', description: 'Faire proposer une mini roadmap en 3 mots.', difficulty: 2, category: MissionCategory.LOGIC },
  { id: 'c071', description: 'Faire dire “on fait un atelier”.', difficulty: 1, category: MissionCategory.HUMOR },
  { id: 'c072', description: 'Faire choisir un mot de passe d’équipe.', difficulty: 1, category: MissionCategory.LOGIC },
  { id: 'c073', description: 'Faire inventer un slogan d’équipe en 1 phrase.', difficulty: 2, category: MissionCategory.CREATIVE },
  { id: 'c074', description: 'Faire proposer un “rituel de victoire”.', difficulty: 2, category: MissionCategory.SOCIAL },
  { id: 'c075', description: 'Faire dire “on est alignés” avec un geste.', difficulty: 1, category: MissionCategory.HUMOR },
  { id: 'c076', description: 'Faire choisir un nom de squad “pro”.', difficulty: 2, category: MissionCategory.CREATIVE },
  { id: 'c077', description: 'Faire proposer une mission “icebreaker”.', difficulty: 2, category: MissionCategory.SOCIAL },
  { id: 'c078', description: 'Faire dire “OKR validés”.', difficulty: 1, category: MissionCategory.HUMOR },
  { id: 'c079', description: 'Faire inventer une mini promesse d’équipe.', difficulty: 2, category: MissionCategory.CREATIVE },
  { id: 'c080', description: 'Faire proposer un “plan d’action” en 2 mots.', difficulty: 1, category: MissionCategory.LOGIC },
  { id: 'c081', description: 'Faire dire “on s’aligne” en sourire.', difficulty: 1, category: MissionCategory.HUMOR },
  { id: 'c082', description: 'Faire choisir un slogan pour la soirée.', difficulty: 2, category: MissionCategory.CREATIVE },
  { id: 'c083', description: 'Faire proposer un “feedback rapide”.', difficulty: 1, category: MissionCategory.SOCIAL },
  { id: 'c084', description: 'Faire dire “c’est prioritaire”.', difficulty: 1, category: MissionCategory.HUMOR },
  { id: 'c085', description: 'Faire inventer un nom de feature “fun”.', difficulty: 2, category: MissionCategory.CREATIVE },
  { id: 'c086', description: 'Faire proposer un mini plan de 3 mots.', difficulty: 1, category: MissionCategory.LOGIC },
  { id: 'c087', description: 'Faire dire “on valide”.', difficulty: 1, category: MissionCategory.HUMOR },
  { id: 'c088', description: 'Faire choisir un “owner de la musique”.', difficulty: 1, category: MissionCategory.SOCIAL },
  { id: 'c089', description: 'Faire inventer un pitch en 1 phrase.', difficulty: 2, category: MissionCategory.CREATIVE },
  { id: 'c090', description: 'Faire proposer un mini KPI “rire”.', difficulty: 2, category: MissionCategory.LOGIC },
  { id: 'c091', description: 'Faire dire “je prends l’action”.', difficulty: 1, category: MissionCategory.HUMOR },
  { id: 'c092', description: 'Faire choisir un mot‑buzz officiel.', difficulty: 2, category: MissionCategory.SOCIAL },
  { id: 'c093', description: 'Faire inventer un titre de présentation.', difficulty: 2, category: MissionCategory.CREATIVE },
  { id: 'c094', description: 'Faire dire “ok, next”.', difficulty: 1, category: MissionCategory.HUMOR },
  { id: 'c095', description: 'Faire proposer un plan “B” amusant.', difficulty: 2, category: MissionCategory.LOGIC },
  { id: 'c096', description: 'Faire choisir un mot‑code du groupe.', difficulty: 1, category: MissionCategory.LOGIC },
  { id: 'c097', description: 'Faire dire “on garde le cap”.', difficulty: 1, category: MissionCategory.HUMOR },
  { id: 'c098', description: 'Faire proposer un mini “retro”.', difficulty: 2, category: MissionCategory.SOCIAL },
  { id: 'c099', description: 'Faire inventer un logo décrit en 3 mots.', difficulty: 2, category: MissionCategory.CREATIVE },
  { id: 'c100', description: 'Faire dire “tout est aligné”.', difficulty: 1, category: MissionCategory.HUMOR },
];

export const CHILL_MISSIONS: Mission[] = [
  { id: 's001', description: 'Faire choisir une chanson chill.', difficulty: 1, category: MissionCategory.SOCIAL },
  { id: 's002', description: 'Faire décrire un souvenir sympa en une phrase.', difficulty: 1, category: MissionCategory.SOCIAL },
  { id: 's003', description: 'Faire proposer un snack idéal.', difficulty: 1, category: MissionCategory.CREATIVE },
  { id: 's004', description: 'Faire répondre à “thé ou café ?”.', difficulty: 1, category: MissionCategory.LOGIC },
  { id: 's005', description: 'Faire écrire un emoji qui décrit l’humeur.', difficulty: 1, category: MissionCategory.HUMOR },
  { id: 's006', description: 'Faire choisir une couleur pour la soirée.', difficulty: 1, category: MissionCategory.CREATIVE },
  { id: 's007', description: 'Faire raconter une anecdote en 10 secondes.', difficulty: 2, category: MissionCategory.SOCIAL },
  { id: 's008', description: 'Faire proposer une activité tranquille.', difficulty: 1, category: MissionCategory.SOCIAL },
  { id: 's009', description: 'Faire deviner un mot avec un geste.', difficulty: 2, category: MissionCategory.PERFORMANCE },
  { id: 's010', description: 'Faire dire merci à un autre joueur.', difficulty: 1, category: MissionCategory.SOCIAL },
  { id: 's011', description: 'Faire dire “on garde le flow”.', difficulty: 1, category: MissionCategory.HUMOR },
  { id: 's012', description: 'Faire choisir un coin calme.', difficulty: 1, category: MissionCategory.SOCIAL },
  { id: 's013', description: 'Faire choisir un moment chill.', difficulty: 1, category: MissionCategory.SOCIAL },
  { id: 's014', description: 'Faire proposer un jeu soft.', difficulty: 1, category: MissionCategory.SOCIAL },
  { id: 's015', description: 'Faire dire un mot positif sur quelqu’un.', difficulty: 1, category: MissionCategory.SOCIAL },
  { id: 's016', description: 'Faire choisir une boisson sans alcool.', difficulty: 1, category: MissionCategory.SOCIAL },
  { id: 's017', description: 'Faire raconter un souvenir drôle mais doux.', difficulty: 2, category: MissionCategory.SOCIAL },
  { id: 's018', description: 'Faire proposer un bon plan détente.', difficulty: 1, category: MissionCategory.SOCIAL },
  { id: 's019', description: 'Faire choisir un mot cool à dire ce soir.', difficulty: 1, category: MissionCategory.HUMOR },
  { id: 's020', description: 'Faire choisir une couleur d’ambiance.', difficulty: 1, category: MissionCategory.CREATIVE },
  { id: 's021', description: 'Faire poser une question “préférerais‑tu”.', difficulty: 2, category: MissionCategory.LOGIC },
  { id: 's022', description: 'Faire proposer un coin photo.', difficulty: 1, category: MissionCategory.CREATIVE },
  { id: 's023', description: 'Faire choisir un rituel léger.', difficulty: 1, category: MissionCategory.SOCIAL },
  { id: 's024', description: 'Faire dire un mot de bienvenue à quelqu’un.', difficulty: 1, category: MissionCategory.SOCIAL },
  { id: 's025', description: 'Faire choisir un son pour la soirée.', difficulty: 1, category: MissionCategory.HUMOR },
  { id: 's026', description: 'Faire proposer un mini défi ultra simple.', difficulty: 2, category: MissionCategory.SOCIAL },
  { id: 's027', description: 'Faire deviner un objet de la pièce.', difficulty: 2, category: MissionCategory.LOGIC },
  { id: 's028', description: 'Faire dire “pause” et sourire.', difficulty: 1, category: MissionCategory.HUMOR },
  { id: 's029', description: 'Faire choisir un mot secret pour 2 minutes.', difficulty: 2, category: MissionCategory.LOGIC },
  { id: 's030', description: 'Faire proposer une règle respect rigolote.', difficulty: 1, category: MissionCategory.SOCIAL },
  { id: 's031', description: 'Faire choisir un coin cozy.', difficulty: 1, category: MissionCategory.SOCIAL },
  { id: 's032', description: 'Faire proposer une mini pause musique.', difficulty: 1, category: MissionCategory.SOCIAL },
  { id: 's033', description: 'Faire dire “tranquille” avec un sourire.', difficulty: 1, category: MissionCategory.HUMOR },
  { id: 's034', description: 'Faire choisir un objet “calme”.', difficulty: 1, category: MissionCategory.CREATIVE },
  { id: 's035', description: 'Faire raconter un moment préféré de la semaine.', difficulty: 1, category: MissionCategory.SOCIAL },
  { id: 's036', description: 'Faire choisir une activité calme à deux.', difficulty: 1, category: MissionCategory.SOCIAL },
  { id: 's037', description: 'Faire dire “merci” à la pièce.', difficulty: 1, category: MissionCategory.HUMOR },
  { id: 's038', description: 'Faire proposer un snack doux.', difficulty: 1, category: MissionCategory.CREATIVE },
  { id: 's039', description: 'Faire choisir une couleur “zen”.', difficulty: 1, category: MissionCategory.CREATIVE },
  { id: 's040', description: 'Faire dire un mot doux à quelqu’un.', difficulty: 1, category: MissionCategory.SOCIAL },
  { id: 's041', description: 'Faire choisir un petit rituel de fin.', difficulty: 1, category: MissionCategory.SOCIAL },
  { id: 's042', description: 'Faire proposer une mini sieste imaginaire.', difficulty: 1, category: MissionCategory.HUMOR },
  { id: 's043', description: 'Faire choisir un mot “calme” pour 2 minutes.', difficulty: 2, category: MissionCategory.LOGIC },
  { id: 's044', description: 'Faire dire “on souffle”.', difficulty: 1, category: MissionCategory.HUMOR },
  { id: 's045', description: 'Faire proposer une activité en duo tranquille.', difficulty: 1, category: MissionCategory.SOCIAL },
  { id: 's046', description: 'Faire choisir un coin lecture imaginaire.', difficulty: 1, category: MissionCategory.CREATIVE },
  { id: 's047', description: 'Faire raconter un souvenir paisible.', difficulty: 1, category: MissionCategory.SOCIAL },
  { id: 's048', description: 'Faire dire “tout va bien”.', difficulty: 1, category: MissionCategory.HUMOR },
  { id: 's049', description: 'Faire proposer une mini pause eau.', difficulty: 1, category: MissionCategory.SOCIAL },
  { id: 's050', description: 'Faire choisir un mot “doux” en rime.', difficulty: 1, category: MissionCategory.LOGIC },
  { id: 's051', description: 'Faire proposer un jeu de questions soft.', difficulty: 2, category: MissionCategory.SOCIAL },
  { id: 's052', description: 'Faire choisir un mot qui apaise.', difficulty: 1, category: MissionCategory.HUMOR },
  { id: 's053', description: 'Faire dire “c’est ok”.', difficulty: 1, category: MissionCategory.HUMOR },
  { id: 's054', description: 'Faire proposer une ambiance lumière.', difficulty: 1, category: MissionCategory.CREATIVE },
  { id: 's055', description: 'Faire choisir un coin “photo tranquille”.', difficulty: 1, category: MissionCategory.CREATIVE },
  { id: 's056', description: 'Faire proposer une activité sans pression.', difficulty: 1, category: MissionCategory.SOCIAL },
  { id: 's057', description: 'Faire dire “on chill”.', difficulty: 1, category: MissionCategory.HUMOR },
  { id: 's058', description: 'Faire choisir un mot “calme” à dire.', difficulty: 1, category: MissionCategory.LOGIC },
  { id: 's059', description: 'Faire proposer un moment pause pour le groupe.', difficulty: 1, category: MissionCategory.SOCIAL },
  { id: 's060', description: 'Faire dire “on respire”.', difficulty: 1, category: MissionCategory.HUMOR },
  { id: 's061', description: 'Faire choisir une boisson douce.', difficulty: 1, category: MissionCategory.SOCIAL },
  { id: 's062', description: 'Faire proposer un coin “zen”.', difficulty: 1, category: MissionCategory.CREATIVE },
  { id: 's063', description: 'Faire dire un mot gentil à un joueur.', difficulty: 1, category: MissionCategory.SOCIAL },
  { id: 's064', description: 'Faire choisir un moment calme préféré.', difficulty: 1, category: MissionCategory.SOCIAL },
  { id: 's065', description: 'Faire dire “tout doux”.', difficulty: 1, category: MissionCategory.HUMOR },
  { id: 's066', description: 'Faire proposer une mini pause respiration.', difficulty: 1, category: MissionCategory.SOCIAL },
  { id: 's067', description: 'Faire choisir une musique d’ambiance.', difficulty: 1, category: MissionCategory.SOCIAL },
  { id: 's068', description: 'Faire dire “on relax”.', difficulty: 1, category: MissionCategory.HUMOR },
  { id: 's069', description: 'Faire proposer un snack léger.', difficulty: 1, category: MissionCategory.CREATIVE },
  { id: 's070', description: 'Faire choisir une place confortable.', difficulty: 1, category: MissionCategory.SOCIAL },
  { id: 's071', description: 'Faire dire “c’est tranquille”.', difficulty: 1, category: MissionCategory.HUMOR },
  { id: 's072', description: 'Faire proposer une règle “respect”.', difficulty: 1, category: MissionCategory.SOCIAL },
  { id: 's073', description: 'Faire choisir un mot positif collectif.', difficulty: 1, category: MissionCategory.SOCIAL },
  { id: 's074', description: 'Faire dire “on est bien”.', difficulty: 1, category: MissionCategory.HUMOR },
  { id: 's075', description: 'Faire proposer une activité calme à tous.', difficulty: 1, category: MissionCategory.SOCIAL },
  { id: 's076', description: 'Faire choisir une couleur “douce”.', difficulty: 1, category: MissionCategory.CREATIVE },
  { id: 's077', description: 'Faire dire “tout cool”.', difficulty: 1, category: MissionCategory.HUMOR },
  { id: 's078', description: 'Faire proposer un coin “cozy”.', difficulty: 1, category: MissionCategory.CREATIVE },
  { id: 's079', description: 'Faire choisir un mot apaisant.', difficulty: 1, category: MissionCategory.SOCIAL },
  { id: 's080', description: 'Faire dire “on souffle un peu”.', difficulty: 1, category: MissionCategory.HUMOR },
  { id: 's081', description: 'Faire proposer une mini pause dehors.', difficulty: 1, category: MissionCategory.SOCIAL },
  { id: 's082', description: 'Faire choisir une boisson chaude imaginaire.', difficulty: 1, category: MissionCategory.SOCIAL },
  { id: 's083', description: 'Faire dire “on se pose”.', difficulty: 1, category: MissionCategory.HUMOR },
  { id: 's084', description: 'Faire proposer un petit rituel de début.', difficulty: 1, category: MissionCategory.SOCIAL },
  { id: 's085', description: 'Faire choisir un mot gentil pour le groupe.', difficulty: 1, category: MissionCategory.SOCIAL },
  { id: 's086', description: 'Faire dire “tout doux”.', difficulty: 1, category: MissionCategory.HUMOR },
  { id: 's087', description: 'Faire proposer une mini pause sans bruit.', difficulty: 1, category: MissionCategory.SOCIAL },
  { id: 's088', description: 'Faire choisir une musique calme.', difficulty: 1, category: MissionCategory.SOCIAL },
  { id: 's089', description: 'Faire dire “on chill”.', difficulty: 1, category: MissionCategory.HUMOR },
  { id: 's090', description: 'Faire proposer un moment calme collectif.', difficulty: 1, category: MissionCategory.SOCIAL },
  { id: 's091', description: 'Faire choisir un coin “pause”.', difficulty: 1, category: MissionCategory.SOCIAL },
  { id: 's092', description: 'Faire dire “on est posés”.', difficulty: 1, category: MissionCategory.HUMOR },
  { id: 's093', description: 'Faire proposer une règle calme de 2 minutes.', difficulty: 2, category: MissionCategory.SOCIAL },
  { id: 's094', description: 'Faire choisir un mot “zen” à dire.', difficulty: 1, category: MissionCategory.LOGIC },
  { id: 's095', description: 'Faire dire “tranquille”.', difficulty: 1, category: MissionCategory.HUMOR },
  { id: 's096', description: 'Faire proposer une mini pause boisson.', difficulty: 1, category: MissionCategory.SOCIAL },
  { id: 's097', description: 'Faire choisir un moment calme préféré.', difficulty: 1, category: MissionCategory.SOCIAL },
  { id: 's098', description: 'Faire dire “on respire”.', difficulty: 1, category: MissionCategory.HUMOR },
  { id: 's099', description: 'Faire proposer un coin détente.', difficulty: 1, category: MissionCategory.CREATIVE },
  { id: 's100', description: 'Faire choisir une ambiance douce.', difficulty: 1, category: MissionCategory.CREATIVE },
];
